### ISSUE TITLE
Fix that shit

### ISSUE THREAD

**Issue by superkarli9** [EbonJaeger/perworldinventory-kt#104]
Players are losing their inventories all the damn time and there's no upgrade in that plugin i cant remove it nor fix it ...

**Comment by david-bla** [comment]
Awesome issue report. 
Maybe pwi Team should consider to use this in the contribution and issue guide line.

**Comment by superkarli9** [comment]
Are they even alive? cuz they're not even trying to fix that issue by making backups so that there'll no problem, if they make a feature that ables staff to use a command for a player to bring their last inventory it'd be A'ight otherwise the plugin is awesome but insufficient with these issues

**Comment by EbonJaeger** [comment]
Thanks for the contribution, very useful.

It's hard to fix an issue with little to know information about what's happening when it occurs; thus far none has been forthcoming. Nor do they happen on servers I have access to, so I can't reproduce them.

Backups are not the responsibility of this plugin (or any plugin outside actual plugins for backing up servers), that is the responsibility of the server operator. Nor does it fix any issue, because the issue is still there!

Issue templates have been added, so we'll see what that brings. That is all.
