### ISSUE TITLE
Concern/Question about "on the fly" groups

### ISSUE THREAD

**Issue by Kruize1** [EbonJaeger/perworldinventory-kt#143]
This is not really a bug but a concern/question.

I setup a separate world with Multiverse and named it "world_gold"

But my config was like this the entire time:

groups:
  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    default-gamemode: SURVIVAL

I didn't really know or understand what the message "Creating a new group on the fly for 'world_gold'."   .. meant, because everything seemed to be working as it should.

Then I updated to the latest version, and maybe at some point in time added "world_gold" to my config,

So it looked like this now:

groups:
  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    - world_gold
    default-gamemode: SURVIVAL

Now the problem is, new users who enter "wolrd_gold" keep their inventory from other worlds.

I didn't want this, so I removed "world_gold" and it's back to making an "on the fly" group. Which is ok ...maybe?

Should I make a second group? 

I'm worried though, will all the existing users in "world_gold" lose their inventories, or lose their inventories in other worlds if I make a second group now?

Is there anyway to find out what this "on the fly" group was , so I can add it to my yml? 

Did I just screw over all my users in "world_gold" ?

**Comment by EbonJaeger** [comment]
A group is created on the fly when a user goes to a world that is not defined in the worlds.yml file. From the sounds of it, you want the inventory of this world separate from the main one, so you want it to be in its own group. It would probably be a good idea to do this in case you decide you want more worlds, and things get more complicated.

Since users already have data and such for this world, you'll want to make its group name the same as the world name, since on the fly groups use the name of the world as the group name. 

You can also use the in-game (or console) commands to create, edit, and manage your world groups. This is safer than editing the file by hand. See the wiki here on Github for more details.

**Comment by Kruize1** [comment]
Thanks very much for your quick reply.

In terms of naming convention? Name the group "world_gold" and add the group "world_gold"? Like this? 

groups:
  default:
    worlds:
- world
- world_nether
- world_the_end
    default-gamemode: SURVIVAL
  world_gold:
    worlds:
    - world_gold
    default-gamemode: SURVIVAL

**Comment by EbonJaeger** [comment]
Yes.

**Comment by Kruize1** [comment]
Thank you very much!
